version: "3.4"

services:

     mysql:
          image: mariadb:latest
          container_name: mariadb-local
          ports:
               - "30000:3306"
          volumes:
               - mysql_vol:/var/lib/data
               - ./csv_data:/csv_data
          environment:
               MYSQL_ROOT_PASSWORD: root
               MYSQL_DATABASE: avions

     phpmyadmin:
          image: phpmyadmin/phpmyadmin
          container_name: phpmyadmin-local
          ports:
               - "30080:80"
          volumes:
               - ./csv_data:/csv_data
          environment: 
               PMA_HOST: mysql
               MYSQL_ROOT_PASSWORD: root

             
volumes:
     mysql_vol:
