CREATE TABLE IF NOT EXISTS flights(
    year YEAR NOT NULL,month TINYINT UNSIGNED NOT NULL,
    day TINYINT UNSIGNED NOT NULL,
    dep_time TIME ,
    sched_dep_time TIME ,
    dep_delay SMALLINT ,
    arr_delay SMALLINT ,
    arr_time TIME NOT NULL,
    sched_arr_time TIME ,
    carrier CHAR(2) NOT NULL,
    flight SMALLINT UNSIGNED PRIMARY KEY,
    tailnum CHAR(6) ,
    origin CHAR(3) NOT NULL,
    dest CHAR(3) NOT NULL,
    air_time SMALLINT UNSIGNED ,
    distance SMALLINT UNSIGNED NOT NULL,
    hour TINYINT UNSIGNED NOT NULL,
    minute TINYINT UNSIGNED NOT NULL,
    time_hour DATETIME NOT NULL,
    CONSTRAINT FK_origin FOREIGN KEY (origin) REFERENCES airports(faa) ON DELETE CASCADE,
    CONSTRAINT FK_dest FOREIGN KEY (dest) REFERENCES airports(faa) ON DELETE CASCADE,
    CONSTRAINT FK_composite FOREIGN KEY (`year`,`month`,`day`,`hour`) REFERENCES weather(`year`,`month`,`day`,`hour`) ON DELETE CASCADE
)