CREATE TABLE IF NOT EXISTS airlines (
    carrier CHAR(2) PRIMARY KEY, 
    name VARCHAR(100) NOT NULL
)

LOAD DATA INFILE '/csv_data/airlines.csv'
INTO TABLE airlines
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS