CREATE TABLE IF NOT EXISTS airports (
    faa CHAR(4) PRIMARY KEY, 
    name VARCHAR(100) NOT NULL, 
    lat FLOAT NOT NULL, 
    lon FLOAT NOT NULL, 
    alt SMALLINT NOT NULL, 
    tz TINYINT NOT NULL, 
    dst CHAR(1) NOT NULL, 
    tzone VARCHAR(100) NOT NULL
)